rank = [
    (358, 'RXNORM', 'BN', 'N'),
    (363, 'RXNORM', 'BPCK', 'N'),
    (360, 'RXNORM', 'DF', 'N'),
    (361, 'RXNORM', 'DFG', 'N'),
    (50, 'RXNORM', 'ET', 'N'),
    (362, 'RXNORM', 'GPCK', 'N'),
    (369, 'RXNORM', 'IN', 'N'),
    (367, 'RXNORM', 'MIN', 'N'),
    (357, 'RXNORM', 'PIN', 'N'),
    (368, 'RXNORM', 'PSN', 'N'),
    (372, 'RXNORM', 'SBD', 'N'),
    (359, 'RXNORM', 'SBDC', 'N'),
    (365, 'RXNORM', 'SBDF', 'N'),
    (370, 'RXNORM', 'SBDG', 'N'),
    (373, 'RXNORM', 'SCD', 'N'),
    (364, 'RXNORM', 'SCDC', 'N'),
    (366, 'RXNORM', 'SCDF', 'N'),
    (371, 'RXNORM', 'SCDG', 'N'),
    (355, 'RXNORM', 'SY', 'N'),
    (356, 'RXNORM', 'TMSY', 'N')
]

rank_by_tty = {
    'TMSY': [19],
    'SY': [18],
    'PSN': [9],
    'SCDC': [15],
    'PIN': [8],
    'MIN': [7],
    'DF': [2],
    'SCD': [14],
    'BN': [0],
    'GPCK': [5],
    'BPCK': [1],
    'SCDG': [17],
    'SBD': [10],
    'IN': [6],
    'SBDC': [11],
    'ET': [4],
    'DFG': [3],
    'SBDG': [13],
    'SBDF': [12],
    'SCDF': [16]
}
